name: Sync and merge upstream repository
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 15 * * *" # 매일 자정 실행

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'thumbzzero'
          git config --global user.email 'thumbzzero@gmail.com'
          git pull --unshallow
          git remote add upstream https://github.com/YeolJyeongKong/fittering-FE.git
          git fetch upstream
          git checkout main
          git merge -Xtheirs upstream/main
          git push origin main
